generate: mainwindow.py filters.py comment.py like.py follow_unfollow.py loginform.py status.py

%.py:%.ui
	pyuic5 $<  > $@
clean:
	rm mainwindow.py filters.py comment.py like.py follow_unfollow.py loginform.py status.py

