# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'status.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(586, 461)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.widget_9 = QtWidgets.QWidget(Form)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.widget_9)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.cur_tab = QtWidgets.QWidget()
        self.cur_tab.setObjectName("cur_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cur_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.cur_tab)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(55, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cur_like = QtWidgets.QLineEdit(self.widget)
        self.cur_like.setReadOnly(True)
        self.cur_like.setObjectName("cur_like")
        self.horizontalLayout.addWidget(self.cur_like)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.cur_tab)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(55, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cur_follow = QtWidgets.QLineEdit(self.widget_2)
        self.cur_follow.setReadOnly(True)
        self.cur_follow.setObjectName("cur_follow")
        self.horizontalLayout_2.addWidget(self.cur_follow)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.cur_tab)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setMinimumSize(QtCore.QSize(55, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cur_unfollow = QtWidgets.QLineEdit(self.widget_3)
        self.cur_unfollow.setReadOnly(True)
        self.cur_unfollow.setObjectName("cur_unfollow")
        self.horizontalLayout_3.addWidget(self.cur_unfollow)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.cur_tab)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setMinimumSize(QtCore.QSize(55, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cur_comment = QtWidgets.QLineEdit(self.widget_4)
        self.cur_comment.setReadOnly(True)
        self.cur_comment.setObjectName("cur_comment")
        self.horizontalLayout_4.addWidget(self.cur_comment)
        self.verticalLayout.addWidget(self.widget_4)
        self.tabWidget.addTab(self.cur_tab, "")
        self.life_tab = QtWidgets.QWidget()
        self.life_tab.setObjectName("life_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.life_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_8 = QtWidgets.QWidget(self.life_tab)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.widget_8)
        self.label_8.setMinimumSize(QtCore.QSize(55, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.file_like = QtWidgets.QLineEdit(self.widget_8)
        self.file_like.setReadOnly(True)
        self.file_like.setObjectName("file_like")
        self.horizontalLayout_8.addWidget(self.file_like)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_5 = QtWidgets.QWidget(self.life_tab)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setMinimumSize(QtCore.QSize(55, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.life_follow = QtWidgets.QLineEdit(self.widget_5)
        self.life_follow.setReadOnly(True)
        self.life_follow.setObjectName("life_follow")
        self.horizontalLayout_5.addWidget(self.life_follow)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.life_tab)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setMinimumSize(QtCore.QSize(55, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.life_unfollow = QtWidgets.QLineEdit(self.widget_6)
        self.life_unfollow.setReadOnly(True)
        self.life_unfollow.setObjectName("life_unfollow")
        self.horizontalLayout_6.addWidget(self.life_unfollow)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.life_tab)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setMinimumSize(QtCore.QSize(55, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.life_comment = QtWidgets.QLineEdit(self.widget_7)
        self.life_comment.setReadOnly(True)
        self.life_comment.setObjectName("life_comment")
        self.horizontalLayout_7.addWidget(self.life_comment)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.tabWidget.addTab(self.life_tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.verticalLayout_4.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_10.addWidget(self.widget_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Likes"))
        self.label_2.setText(_translate("Form", "Follows"))
        self.label_3.setText(_translate("Form", "Unfollows"))
        self.label_4.setText(_translate("Form", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cur_tab), _translate("Form", "&Current Session"))
        self.label_8.setText(_translate("Form", "Likes"))
        self.label_5.setText(_translate("Form", "Follows"))
        self.label_6.setText(_translate("Form", "Unfollows"))
        self.label_7.setText(_translate("Form", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.life_tab), _translate("Form", "&Lifetime "))
        self.label_9.setText(_translate("Form", "Stat for activities of bot"))
